GTNewHorizons/GTNHLib

src/main/java/com/gtnewhorizon/gtnhlib/util/map/ItemStackMap.java
Should work for Hodgepodge Furnace Fix (NBT insensitive option), and any other place that needs to use it.
=> ItemStackMap

src/main/java/com/gtnewhorizon/gtnhlib/ClientProxy.java, src/main/java/com/gtnewhorizon/gtnhlib/CommonProxy.java, src/main/java/com/gtnewhorizon/gtnhlib/util/AboveHotbarHUD.java
By the request of @Alexdoru I added the method to GTNHLib to be used anywhere else by whoever wants it.
=> Adds a way to display a message above the hotbar

build.gradle, src/main/java/com/gtnewhorizon/gtnhlib/ClientProxy.java, src/main/java/com/gtnewhorizon/gtnhlib/CommonProxy.java, src/main/java/com/gtnewhorizon/gtnhlib/util/AnimatedTooltipHandler.java
Extracted from https://github.com/GTNewHorizons/GT5-Unofficial/blob/master/src/main/java/gregtech/client/GT_TooltipEventHandler.java.
=> Add Tooltip Animation API

src/main/java/com/gtnewhorizon/gtnhlib/util/AnimatedTooltipHandler.java
=> Improve Tooltip Animation API

src/main/java/com/gtnewhorizon/gtnhlib/util/AnimatedTooltipHandler.java
Add helper methods for animated and/or formatted static/animated tooltips.
=> More Tooltip Animation Options

src/main/java/com/gtnewhorizon/gtnhlib/util/map/ItemStackMap.java
fix https://github.com/GTNewHorizons/Hodgepodge/issues/165
=> iterator return without wildcard tag if not nbt sensitive

build.gradle, src/main/java/com/gtnewhorizon/gtnhlib/ClientProxy.java, src/main/java/com/gtnewhorizon/gtnhlib/reflect/Fields.java
=> Fix broken mod

README.md, dependencies.gradle, src/main/java/com/gtnewhorizon/gtnhlib/config/Config.java, src/main/java/com/gtnewhorizon/gtnhlib/config/ConfigException.java, src/main/java/com/gtnewhorizon/gtnhlib/config/ConfigurationManager.java, src/main/java/com/gtnewhorizon/gtnhlib/config/IConfigElementProxy.java, src/main/java/com/gtnewhorizon/gtnhlib/config/SimpleGuiConfig.java, src/main/java/com/gtnewhorizon/gtnhlib/config/SimpleGuiFactory.java
This will allow our mods to easily create config files as well as allow them to be editable in game from the Forge config menu.
Should we also move this to here or even HP?
https://github.com/GTNewHorizons/EnderCore/blob/master/src/main/java/com/enderio/core/client/gui/bettermodlist/EventHandlerGui.java
This allows the forge config gui to work in game.
=> Port configs from Angelica/ArchaicFix

dependencies.gradle
Adds a shadow for JOML, which is being moved from Angelica to be more generally available to GTNH mods.
=> Shadow JOML

src/main/java/com/gtnewhorizon/gtnhlib/util/parsing/MathExpressionParser.java, src/test/java/com/gtnewhorizon/gtnhlib/test/util/parsing/MathExpressionParserTest.java
Adds a class for parsing mathematical expressions from here: https://github.com/GTNewHorizons/ModularUI/pull/60
The only difference from this PR is slight renaming to fit the context of a library function better, and comments/javadocs.
=> Added MathExpressionParser.

src/main/java/com/gtnewhorizon/gtnhlib/config/Config.java, src/main/java/com/gtnewhorizon/gtnhlib/config/ConfigurationManager.java
Accidentally made them required
=> Remove required parameter to Config annotation

src/main/java/com/gtnewhorizon/gtnhlib/asm/ClassConstantPoolParser.java
Move over from Angelica for broader use
=> Add ClassConstantPoolParser

addon.gradle, dependencies.gradle, src/main/java/com/gtnewhorizon/gtnhlib/util/CoordinatePacker.java, src/test/java/com/gtnewhorizon/gtnhlib/test/util/CoordinatePackerTest.java
* Currently used in Angelica & GT5u
=> Add CoordinatePacker

src/main/java/com/gtnewhorizon/gtnhlib/core/MixinCompatHackTweaker.java, src/main/java/com/gtnewhorizon/gtnhlib/mixins/Mixins.java
Fixes an issue with Optifine crashing with the CapturingTessalator
=> Dont CapturingTessalator if OF/FC is loaded

src/main/java/com/gtnewhorizon/gtnhlib/ClientProxy.java, src/main/java/com/gtnewhorizon/gtnhlib/client/model/ModelLoader.java
Also only load models if at least one has been registered.
=> Move model loading to GTNHLib

src/main/java/com/gtnewhorizon/gtnhlib/client/renderer/CapturingTessellator.java, src/main/java/com/gtnewhorizon/gtnhlib/core/MixinCompatHackTweaker.java, src/main/java/com/gtnewhorizon/gtnhlib/core/transformer/TessellatorRedirectorTransformer.java, src/main/java/com/gtnewhorizon/gtnhlib/mixins/Mixins.java
no reason to transform the Tessellator itself anyway...
Should fix: https://github.com/GTNewHorizons/GTNHLib/issues/53
=> This should fix compat with OF & FT; 

src/main/java/com/gtnewhorizon/gtnhlib/config/ConfigurationManager.java
=> Merge the same filename configs

src/main/java/com/gtnewhorizon/gtnhlib/client/renderer/util/WorldUtil.java
needed by https://github.com/GTNewHorizons/Angelica/pull/642
=> account for vanilla fluid blocks

src/main/java/com/gtnewhorizon/gtnhlib/util/FilesUtil.java
moved from https://github.com/GTNewHorizons/Angelica/blob/fd78f63f12f39de2871222b50357c526e861fb8e/src/main/java/net/coderbot/iris/gui/screen/ShaderPackScreen.java#L409
=> add util to open files / urls on every OS

src/main/java/com/gtnewhorizon/gtnhlib/core/transformer/EventBusSubTransformer.java
Transforms the methods at runtime to make them public. This is mostly so we can hide the methods from the compiler which I find more important now that they're static.
=> Allow non-public subscribed methods in @EventBusSubscriber classes

src/main/java/com/gtnewhorizon/gtnhlib/asm/ClassConstantPoolParser.java, src/main/java/com/gtnewhorizon/gtnhlib/core/GTNHLibCore.java
Most of this is just refactoring to make the code more readable. Also excludes the ASM utils from transformation.
=> Update the constant pool parser for Java 25

gradle.properties
`d` refers to literal alphabet
=> Fix versionPattern

src/main/java/com/gtnewhorizon/gtnhlib/client/renderer/stacks/IStateStack.java
* Add javadoc strings and add a clear() method
=> Updates for IStateStack

src/main/java/com/gtnewhorizon/gtnhlib/core/GTNHLibCore.java, src/main/java/com/gtnewhorizon/gtnhlib/mixin/IMixins.java, src/main/java/com/gtnewhorizon/gtnhlib/mixin/ITargetedMod.java, src/main/java/com/gtnewhorizon/gtnhlib/mixin/MixinBuilder.java, src/main/java/com/gtnewhorizon/gtnhlib/mixin/Phase.java, src/main/java/com/gtnewhorizon/gtnhlib/mixin/Side.java, src/main/java/com/gtnewhorizon/gtnhlib/mixin/TargetedMod.java, src/main/java/com/gtnewhorizon/gtnhlib/mixins/Mixins.java
This re-works the mixin infrastructure to be more broadly usable by all mods, so that mods don't need to copy/paste all of this into themselves and can just pull it from GTNHLib. As of right now this is a first pass at what it might look like, looking for comments/ideas on this still.
=> New mixin infrastructure

src/main/java/com/gtnewhorizon/gtnhlib/datastructs/spatialhashgrid/SpatialHashGrid.java, src/main/java/com/gtnewhorizon/gtnhlib/util/DistanceUtil.java, src/test/java/com/gtnewhorizon/gtnhlib/test/datastructs/spatialhashgrid/SpatialHashGridTest.java
Changed default formula to Chebyshev
Added test
=> Update SpatialHashGrid findNearby

src/main/java/com/gtnewhorizon/gtnhlib/client/renderer/shader/ShaderProgram.java
=> add close() to ShaderProgram to free resources

src/main/java/com/gtnewhorizon/gtnhlib/datastructs/space/VolumeMembershipCheck.java
This is a data structure that allows you to quickly check if an arbitrary point in space is contained within at least one of the volumes defined.
It does so by brute forcing through all the positions.
=> add VolumeMembershipCheck

src/main/java/com/gtnewhorizon/gtnhlib/keybind/SyncedKeybind.java
=> Expose SyncedKeybind keyCode

src/main/java/com/gtnewhorizon/gtnhlib/blockpos/BlockPos.java
Old value: `( 9.800E+1  5.700E+1  2.570E+2)`
New value: `(98, 57, 257)`
=> Make BlockPos#toString() more reasonable

src/main/java/com/gtnewhorizon/gtnhlib/datastructs/space/ArrayProximityMap4D.java, src/test/java/com/gtnewhorizon/gtnhlib/test/datastructs/space/ArrayProximityTest.java
fixes : https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/20443
=> fix off by one error in ArrayProximityMap4D.remove
