GTNewHorizons/GTNHLib

src/main/java/com/gtnewhorizon/gtnhlib/util/map/ItemStackMap.java
Implementation defined in superinterface's default method does not know about the internals of map, thus operate with less efficiency, e.g. merge() must do 2 hash lookup instead of one. Implementing these in subclass allow better performance should client code take use of these optional features.
=> Implement some useful optional features to make this faster

build.gradle, dependencies.gradle, src/main/java/com/gtnewhorizon/gtnhlib/reflect/Fields.java, src/test/java/com/gtnewhorizon/gtnhlib/test/reflect/FieldsTestSubject.java, src/test/java/com/gtnewhorizon/gtnhlib/test/reflect/FieldsTests.java
A few mods use hacky code to change the `modifiers` field of `java.lang.reflect.Field` instances, this doesn't work as of Java 12. As the replacement is not trivial, I think putting this in shared code makes more sense, and I can provide a nicer optionally type-checked API for it too.
Includes some simple JUnit tests, I have not tested every primitive type because copy-pasting the same tests 9 times seems a bit silly, but I can't think of another solution. I ran the tests on java versions 8, 11, 17 and 19 and all of them work.
It uses Unsafe, but afaik in modern Java there is no other alternative to write to `final static` fields without removing `final` via class transformation before loading.
=> Add (final static and others) field reflection utilities, compatible with Java 8-19

dependencies.gradle, gradle.properties
Already used in Angelica, although it can be minimized there. This way it can be re-used everywhere though.
Bloats the file size from 50kb to 22MB 💀
=> Add fastutil to dependencies.gradle

src/main/java/com/gtnewhorizon/gtnhlib/config/Config.java
Unlike `Integer.MIN_VALUE`, `Float.MIN_VALUE` is actually the smallest, positive non-zero number (2<sup>-149</sup>).
=> Fix lower bound of `@Config.RangeFloat`

src/main/java/com/gtnewhorizon/gtnhlib/util/parsing/MathExpressionParser.java
The character `’`, used as a thousands separator in Swiss locales, is now valid in expression parsing.
=> Localization fix

src/main/java/com/gtnewhorizon/gtnhlib/concurrent/cas/CasAdapter.java, src/main/java/com/gtnewhorizon/gtnhlib/concurrent/cas/CasList.java, src/main/java/com/gtnewhorizon/gtnhlib/concurrent/cas/CasMap.java, src/test/java/com/gtnewhorizon/gtnhlib/test/concurrent/CasTest.java
Useful for situations of very rare mutations and very frequent concurrent reads.
The CAS wrapper can be used to easily implement it for any fastutil collection, the generic CasList and CasMap serve as a utility for Object collections and implementation reference.
=> Add a compare-and-swap reference wrapper and collections

src/main/java/com/gtnewhorizon/gtnhlib/core/GTNHLibCore.java, src/main/java/com/gtnewhorizon/gtnhlib/core/MixinCompatHackTweaker.java
Tested w/ java 8 & Angelica beta 4
```
angelica-1.0.0-beta4.jar
archaicfix-0.7.0.jar
CodeChickenCore-1.3.6.jar
CoreTweaks-1.7.10-0.3.3.2+nomixin.jar
gtnhlib-0.4.2.jar
NotEnoughItems-2.6.19-GTNH.jar
+unimixins-all-1.7.10-0.1.15.jar
```
=> Add the MixinCompatHackTweaker to fix running on java 8 w/o lwjgl3ify/rfbplugin

src/main/java/com/gtnewhorizon/gtnhlib/core/transformer/TessellatorRedirectorTransformer.java
They also need to be checked when RFB is not present and the transformer is going through the legacy transformer pipeline.
=> Fix transformer exclusions when loading without RFB

src/main/java/com/gtnewhorizon/gtnhlib/config/Config.java, src/main/java/com/gtnewhorizon/gtnhlib/config/ConfigFieldParser.java, src/main/java/com/gtnewhorizon/gtnhlib/config/ConfigurationManager.java
1. Fixes subcats having their category name twice in the langkey & stops subcats from having their lang key set multiple times.
2. Makes `@Config.Comment` applicable to classes so that you can put the annotation on the subcat class instead of their field & add comments for non-subcategories
3. Adds the `-Dgtnhlib.printkeys` jvm flag to print lang keys generated from `@Config.LangKeyPattern` in the log.
=> Fix a few config issues

src/main/java/com/gtnewhorizon/gtnhlib/config/ConfigFieldParser.java
If we have an enum config with the following possible values:
VALUE1 - default
VALUE2
Previously If the player inputted `value2` in the config file it will fail to find a matching enum for that and revert back to the default.
This makes it look for a case insensitive match between the input and the valid values, if one is found it will also be saved so that we won't have to go through this process every time.
=> Make config enums ignore case

src/main/java/com/gtnewhorizon/gtnhlib/CommonProxy.java, src/main/java/com/gtnewhorizon/gtnhlib/config/Config.java, src/main/java/com/gtnewhorizon/gtnhlib/config/ConfigurationManager.java
Adds the `-Dgtnhlib.dumpkeys` jvm flag to dump the lang keys generated from LangKeyPattern to a text file in a ready to copy format like so:
```
gtnhlib.test.subconfig.subsubconfig.nestednestedint=
gtnhlib.test.subconfig.subsubconfig=
gtnhlib.test.subconfig.nestedint=
gtnhlib.test.subconfig.testenum2=
gtnhlib.test.subconfig=
gtnhlib.test.testenum=
gtnhlib.test=
```
=> Add jvm flag to dump generated lang keys to file

src/main/java/com/gtnewhorizon/gtnhlib/CommonProxy.java, src/main/java/com/gtnewhorizon/gtnhlib/GTNHLib.java, src/main/java/com/gtnewhorizon/gtnhlib/core/GTNHLibCore.java, src/main/java/com/gtnewhorizon/gtnhlib/core/transformer/EventBusSubTransformer.java, src/main/java/com/gtnewhorizon/gtnhlib/eventbus/AutoEventBus.java, src/main/java/com/gtnewhorizon/gtnhlib/eventbus/EventBusSubscriber.java, src/main/java/com/gtnewhorizon/gtnhlib/eventbus/EventBusUtil.java, src/main/java/com/gtnewhorizon/gtnhlib/eventbus/Phase.java, src/main/java/com/gtnewhorizon/gtnhlib/eventbus/StaticASMEventHandler.java
Invoking the `@EventBusSubscriber.Condition` method suffered from the same reflection problems as described in https://github.com/GTNewHorizons/GTNHLib/pull/80, which is that it will have to load the entire method table including parameters classes that might not be present. 
Having to dynamically invoke a given method without reflection only leaves a few options, which are either using `MethodHandle` which are generally faster than reflection if invoked a ton of times but significantly slower if only invoked once 
or using the semi-obscure `LambdaMetafactory` api. This generates a synthetic anonymous class that implements a functional interface to get a value from the specified method, while that might sound like it would be a lot slower than reflection it was in fact consistently faster …
=> EventBusSubscriber improvements

src/main/java/com/gtnewhorizon/gtnhlib/config/ConfigurationManager.java
Any config values that are no longer in use will stay indefinitely in the config file and also shows up in the config gui.
Take this old boubou test config for instance
```
Test {
subconfig {
subsubconfig {
}
}
}
rossruinsmeta {
}
test {
B:testBool=true
D:testDouble=1.0
S:testEnum=VALUE1
I:testInt=1
S:testString=test
##########################################################################################################
#--------------------------------------------------------------------------------------------------------#
##########################################################################################################
subconfig {
I:nestedInt=2
S:testEnum2=VALUE2
########################################################################################################## …
```
=> Auto remove dead config categories/values from the config file

src/main/java/com/gtnewhorizon/gtnhlib/ClientProxy.java, src/main/java/com/gtnewhorizon/gtnhlib/commands/GTNHClientCommand.java, src/main/java/com/gtnewhorizon/gtnhlib/commands/ItemInHandCommand.java
and move it to GTNHlib so that it's available from every dev environement when using client 17
related pr : https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1051
=> merge iih + mt hand command in one

src/main/java/com/gtnewhorizon/gtnhlib/core/GTNHLibCore.java, src/main/java/com/gtnewhorizon/gtnhlib/debug/TexturesDebug.java, src/main/java/com/gtnewhorizon/gtnhlib/mixins/Mixins.java, src/main/java/com/gtnewhorizon/gtnhlib/mixins/early/debug/MixinDynamicTexture.java, src/main/java/com/gtnewhorizon/gtnhlib/mixins/early/debug/MixinTextureAtlasSprite.java
Using `-Dgtnhlib.debugtextures=true` will now create two files in your `.minecraft` folder that will list all the registered textures in a `csv` file with their name, width, height, amount of frames and the size in bytes it takes in the RAM.
We should use this to point to all the textures that are too large and rework them.
=> Add texture debug feature

build.gradle.kts, dependencies.gradle
The `shadow` plugin doesn't support shading source jars by default, so this adds a way to manually do it. Fastutil and JOML sources will be available in dev envs now, at the cost of a larger sources jar.
=> Shadow source jars too

dependencies.gradle, gradle.properties, repositories.gradle, src/main/java/com/gtnewhorizon/gtnhlib/ClientProxy.java, src/main/java/com/gtnewhorizon/gtnhlib/api/CapturingTesselator.java, src/main/java/com/gtnewhorizon/gtnhlib/client/renderer/TessellatorManager.java, src/main/java/com/gtnewhorizon/gtnhlib/compat/FalseTweaks.java, src/main/java/com/gtnewhorizon/gtnhlib/compat/Mods.java, src/main/java/com/gtnewhorizon/gtnhlib/mixins/Mixins.java, src/main/java/com/gtnewhorizon/gtnhlib/mixins/early/MixinTessellator.java
If FT's threaded rendering is running, it's handling the safety checks itself so skip ours.
=> Disable thread safety checks with FalseTweaks

src/main/java/com/gtnewhorizon/gtnhlib/ClientProxy.java, src/main/java/com/gtnewhorizon/gtnhlib/client/tooltip/LoreHandler.java, src/main/java/com/gtnewhorizon/gtnhlib/client/tooltip/LoreHolder.java
Moved from here: https://github.com/GTNewHorizons/GTNH-Intergalactic/tree/master/src/main/java/com/gtnewhorizons/gtnhintergalactic/client/lore
=> Move lore handler from intergalactic to gtnhlib

src/main/java/com/gtnewhorizon/gtnhlib/api/MusicRecordMetadataProvider.java
First part of fixing https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18055 - adding a standardized interface to list all music disks and get the sound resources corresponding to each disk, even for NBT and metadata-powered disks.
=> Add an interface for meta- and nbt-aware music disks to fix modded disk support in electric jukeboxes

src/main/java/com/gtnewhorizon/gtnhlib/eventbus/AutoEventBus.java, src/main/java/com/gtnewhorizon/gtnhlib/util/data/BlockMeta.java, src/main/java/com/gtnewhorizon/gtnhlib/util/data/BlockSupplier.java, src/main/java/com/gtnewhorizon/gtnhlib/util/data/IMod.java, src/main/java/com/gtnewhorizon/gtnhlib/util/data/ImmutableBlockMeta.java, src/main/java/com/gtnewhorizon/gtnhlib/util/data/ImmutableItemMeta.java, src/main/java/com/gtnewhorizon/gtnhlib/util/data/ItemMeta.java, src/main/java/com/gtnewhorizon/gtnhlib/util/data/ItemStackSupplier.java, src/main/java/com/gtnewhorizon/gtnhlib/util/data/ItemSupplier.java, src/main/java/com/gtnewhorizon/gtnhlib/util/data/Lazy.java, src/main/java/com/gtnewhorizon/gtnhlib/util/data/LazyBlock.java, src/main/java/com/gtnewhorizon/gtnhlib/util/data/LazyItem.java
This PR adds a few util classes that I've needed several times in different mods. I've also seen similar classes replicated a good amount of times, so I figure these should be formalized properly.
If the mutability contract isn't clear, let me know. I tried to make it as robust as possible.
=> Add block/meta and item/meta pair classes

src/main/java/com/gtnewhorizon/gtnhlib/ClientProxy.java, src/main/java/com/gtnewhorizon/gtnhlib/client/tooltip/LoreHandler.java, src/main/java/com/gtnewhorizon/gtnhlib/client/tooltip/LoreHolder.java, src/main/java/com/gtnewhorizon/gtnhlib/client/tooltip/LoreHolderDiscoverer.java, src/main/java/com/gtnewhorizon/gtnhlib/core/GTNHLibCore.java
Improves the LoreHolder system by identifying all fields during construction using FML's ASMDataTable. Previously, all classes containing one or more fields annotated with `@LoreHolder` would have been registered manually using `LoreHandler.registerLoreHolder()`.
=> Automatic LoreHolder Discovery

src/main/java/com/gtnewhorizon/gtnhlib/config/ConfigSyncHandler.java, src/main/java/com/gtnewhorizon/gtnhlib/config/ConfigurationManager.java
I forgot that loads of mods register their config in coremod and it kinda broke down crying when I tried using config sync in one of those mods
=> Register config sync event bus in init

src/main/java/com/gtnewhorizon/gtnhlib/keybind/IKeyPressedListener.java, src/main/java/com/gtnewhorizon/gtnhlib/keybind/PacketKeyDown.java, src/main/java/com/gtnewhorizon/gtnhlib/keybind/PacketKeyPressed.java, src/main/java/com/gtnewhorizon/gtnhlib/keybind/SyncedKeybind.java, src/main/java/com/gtnewhorizon/gtnhlib/network/NetworkHandler.java
Creates a new API for syncing player client key presses to the server for specified keys.
Supports two different types of key checks:
- "Key Held" - If the key is currently being held down by the player
- "Key Pressed" - Fired for a registered set of listeners when the key is pressed
Supports lightweight keybinds for a `Keyboard` key code, wrapped MC `KeyBinding` types with server syncing, and brand new `KeyBinding` binds with configuration available on the controls page like normal
=> Synced Keybinds API

addon.gradle, build.gradle.kts, dependencies.gradle, src/main/java/com/gtnewhorizon/gtnhlib/bytebuf/APIUtil.java, src/main/java/com/gtnewhorizon/gtnhlib/bytebuf/CheckIntrinsics.java, src/main/java/com/gtnewhorizon/gtnhlib/bytebuf/Checks.java, src/main/java/com/gtnewhorizon/gtnhlib/bytebuf/MemoryManage.java, src/main/java/com/gtnewhorizon/gtnhlib/bytebuf/MemoryStack.java, src/main/java/com/gtnewhorizon/gtnhlib/bytebuf/MemoryUtilities.java, src/main/java/com/gtnewhorizon/gtnhlib/bytebuf/MultiReleaseMemCopy.java, src/main/java/com/gtnewhorizon/gtnhlib/bytebuf/MultiReleaseTextDecoding.java, src/main/java/com/gtnewhorizon/gtnhlib/bytebuf/Pointer.java, src/main/java/com/gtnewhorizon/gtnhlib/bytebuf/StackWalkUtil.java, src/main/java/com/gtnewhorizon/gtnhlib/bytebuf/package-info.java, src/main17/java/com/gtnewhorizon/gtnhlib/bytebuf/CheckIntrinsics.java, src/main17/java/com/gtnewhorizon/gtnhlib/bytebuf/MultiReleaseMemCopy.java, src/main17/java/com/gtnewhorizon/gtnhlib/bytebuf/MultiReleaseTextDecoding.java, src/main17/java/com/gtnewhorizon/gtnhlib/bytebuf/StackWalkUtil.java
Backports LWJGL3's MemoryUtil and MemoryStack for full Java 8 game version compatibility. This allows for much more efficient ByteBuffer allocation, reallocation, address manipulation and access.
The following changes were made to the original implementation:
- Remove dependency on JNI libraries because we don't ship lwjgl 3's libraries in the java 8 build
- Fall back to lwjgl3's implementations when Java 17 or newer is loaded (using the multi-release jar functionality of the JVM, see src/main17)
- Rename MemoryUtil to MemoryUtilities - mainly to make it easier to read autocomplete hints by IntellIJ, but also disambiguate for future mods that use lwjgl3 directly.
- Reimplement the PointerBuffer methods to use lwjgl2's PointerBuffer which is pretty different from 3's
- Remove the …
=> Backport LWJGL3 memory utilities to enable more efficient ByteBuffer usage

src/main/java/com/gtnewhorizon/gtnhlib/keybind/SyncedKeybind.java
Fixes the lwjgl keyboard event key still being checked sometimes when a MC keybinding is set, which shouldn't happen. Also sets the key code to -1 by default, to avoid any other potential oddities
=> Fix MC keybinding-backed synced keybind listeners

gradle.properties, settings.gradle, src/main/java/com/gtnewhorizon/gtnhlib/ClientProxy.java, src/main/java/com/gtnewhorizon/gtnhlib/CommonProxy.java, src/main/java/com/gtnewhorizon/gtnhlib/GTNHLibConfig.java, src/main/java/com/gtnewhorizon/gtnhlib/compat/Mods.java, src/main/java/com/gtnewhorizon/gtnhlib/compat/NotEnoughItemsVersionChecker.java, src/main/java/com/gtnewhorizon/gtnhlib/util/FilesUtil.java
This PR adds a check which runs the first time the player enters any world. If NEI is present and older than 2.7.8-GTNH, a warning will be printed to the chat informing the player that RenderTooltipEvents won't work. This check can be disabled via a config property. I favor this approach over simply adding `before:NotEnoughItems@[2.7.8-GTNH,)` in the `@Mod` annotation because this still allows the use of older NEI versions if RenderTooltipEvents aren't used.
This PR also sets `versionPattern` to prevent future mistakes in that area.
=> Add NEI Version Check

src/main/java/com/gtnewhorizon/gtnhlib/client/event/LivingEquipmentChangeEvent.java, src/main/java/com/gtnewhorizon/gtnhlib/mixins/Mixins.java, src/main/java/com/gtnewhorizon/gtnhlib/mixins/early/MixinEntityLivingBase.java
Adds a forge event which is fired whenever a LivingEntity updates their equipment (armor or main hand item)
This is backported from https://github.com/MinecraftForge/MinecraftForge/pull/3411/ and will be used for armor effects in GTNH.
Short image explanation of the mixin target:
=> Add mixin to register LivingEquipmentChangeEvent

src/main/java/com/gtnewhorizon/gtnhlib/client/tooltip/LoreHandler.java, src/main/java/com/gtnewhorizon/gtnhlib/client/tooltip/LoreHolderDiscoverer.java
Tested and works fine in 2.7.3 and latest
Closes https://github.com/GTNewHorizons/GTNHLib/issues/106
=> Move LoreHolder registration to a later init stage

dependencies.gradle, settings.gradle, src/main/java/com/gtnewhorizon/gtnhlib/client/opengl/UniversalVAO.java
This adds a simple wrapper around GL Vertex Array Objects, using the GL 3.0 API if available, the Apple extension on macs for macOS compatibility and the ARB extension on other 2.1-only drivers. This should cover all the hardware+drivers Minecraft does and allows using VAOs in 2.1 contexts safely.
=> Add VAO utilities for easier core profile compatibility

src/main/java/com/gtnewhorizon/gtnhlib/blockpos/BlockPos.java
This PR replaces the return type of methods in BlockPos, but not changing the IBlockPos interface.
Idk if it ABI compat, but it does API compat.
This fixes the problem that you'll need to cast the return values to BlockPos, when you maintaining a Collection of BlockPos.
In newer forges/fabrics (e.g.: 1.12.2), there isn't a IBlockPos interface, so all methods return BlockPos. It is misleading.
And one more reason is that, BlockPos is _mutable_, so at least the return types should be `IMutableBlockPos` instead of `IBlockPos`, because it loses the set methods.
=> Make BlockPos modifications return BlockPos instead of IBlockPos

src/main/java/com/gtnewhorizon/gtnhlib/blockpos/BlockPos.java, src/main/java/com/gtnewhorizon/gtnhlib/blockpos/IBlockPos.java
This PR adds `#offset(int, int, int)` and `#copy()` to BlockPos, because they are missing.
=> Added offset(int, int, int) and copy() for BlockPos

src/main/java/com/gtnewhorizon/gtnhlib/mixins/Mixins.java, src/main/java/com/gtnewhorizon/gtnhlib/mixins/early/MixinMinecraftServer.java, src/main/java/com/gtnewhorizon/gtnhlib/util/ServerThreadUtil.java
Backport callFromMainThread() and addScheduledTask() of MinecraftServer from 1.12.2
The executing timing is exactly same to what 1.12 Forge does.
And because of my Mixin knowledge limit, I can only get the server thread like that.
These functions are used to do something in server thread, submitted from other threads, like async tasks. (although it checks if the calling thread is the server thread, like 1.12 does)
=> Backport callFromMainThread() and addScheduledTask()

src/main/java/com/gtnewhorizon/gtnhlib/hash/Fnv1a32.java, src/main/java/com/gtnewhorizon/gtnhlib/hash/Fnv1a64.java
Bad hash functions have come up multiple times in mods, this wraps the really simple but still relatively good [FNV-1a](http://www.isthe.com/chongo/tech/comp/fnv/index.html) non-cryptographic hash functions in an allocation-free utility class for both the 32- and 64-bit variants.
There are some additional avalanche utilities available in fastutil (`HashCommon`) if extra mixing of bits is needed after profiling hash bucket collisions.
=> Add 32-bit and 64-bit FNV-1a hash function utilities

src/main/java/com/gtnewhorizon/gtnhlib/util/ObjectPooler.java
Release whole collections at once, instead of having to iteratively do it.
=> Add convenience method to ObjectPooler

src/main/java/com/gtnewhorizon/gtnhlib/datastructs/spatialhashgrid/SpatialHashGrid.java, src/test/java/com/gtnewhorizon/gtnhlib/test/datastructs/spatialhashgrid/SpatialHashGridTest.java, src/test/java/com/gtnewhorizon/gtnhlib/test/datastructs/spatialhashgrid/TestObject.java
I reimplemented the GridIterator, so it wont need any allocs now. 
I also changed it to accept any arbitrary distance calculator and removed the duplicate code spam
In theory the grid should also accept null objects now, at least the grid iterator should work with them, but i didnt really test that, and i also dont think that thats really important
=> Rework spatial hash grid
